name: Astronomy Engine Unit Tests
on: [push]
jobs:
  Astronomy-Engine:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-11, windows-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to path
      if: startsWith(matrix.os, 'windows')
      uses: microsoft/setup-msbuild@v1.1
    - name: Init dotnet core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Init Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install Python linter
      run: python -m pip install --upgrade pip && pip install pylint
    - name: Install documentation tools Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt install -y doxygen xsltproc
    - name: Install documentation tools macOs
      if: startsWith(matrix.os, 'macOS')
      run: HOMEBREW_NO_AUTO_UPDATE=1 brew install doxygen
    - name: Init Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: gradle/wrapper-validation-action@v1

    - name: Test Astronomy Engine Linux
      if: startsWith(matrix.os, 'ubuntu')
      run: cd generate && rm -f output/vsop*.txt output/*.eph output/jupiter_moons.txt && ./run && ./verify_clean

    - name: Test Astronomy Engine macOs
      if: startsWith(matrix.os, 'macOS')
      run: cd generate && rm -f output/vsop*.txt output/*.eph output/jupiter_moons.txt && ./run && ./verify_clean

    - name: Test Astronomy Engine Windows
      if: startsWith(matrix.os, 'windows')
      shell: cmd
      run: call generate\commit_hook.bat
